### PR TITLE
UI improved and Added responsiveness

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**

### CODE REVIEW

**Comment by gouri-panda** [comment]
@BhuvaneshPatil There is conflict. Please solve the conflicts first.

**Comment by BhuvaneshPatil** [comment]
> @BhuvaneshPatil There is conflict. Please solve the conflicts first.

ok

**Comment by gouri-panda** [comment]
Also, that's a lot of changes. You should break into small parts of commits. Also, can you add descriptions in the PR what change have you made and why?

**Comment by BhuvaneshPatil** [comment]
> Also, that's a lot of changes. You should break into small parts of commits. Also, can you add descriptions in the PR what change have you made and why?

I just added few classes and did some changes in css file.I have resolved issue.Maybe I did something wrong during git push I think.

**Comment by gouri-panda** [comment]
ok, update your project with the base project then start changing.

**Comment by gouri-panda** [comment]
@BhuvaneshPatil Are you having some difficulties with this PR?

**Comment by BhuvaneshPatil** [comment]
> @BhuvaneshPatil Are you having some difficulties with this PR?

yes..

**Pull request closed without merging**
