### PR TITLE
Added title field

### PR DESCRIPTION
**Pull request by stanjdev**
Screen Shot 2020-10-04 at 10 48 02 PM

How does this look? @gouri-panda 

#21

### CODE REVIEW

**Comment by gouri-panda** [comment]
@stanjdev It looks good.Is description field optional?

**Comment by stanjdev** [comment]
> @stanjdev It looks good.Is description field optional?

It's not, I can make it optional if you'd like?

**Comment by gouri-panda** [comment]
@stanjdev Please go ahead!

**Comment by stanjdev** [comment]
The description field is now optional and I removed the red border and warning sign for it!

**Review by gouri-panda — APPROVED** [review]

**Comment by gouri-panda** [comment]
@stanjdev Thanks for the PR 🎉.Good work.

**Comment by stanjdev** [comment]
@gouri-panda Thank you!

**Pull request merged**
